---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: repo-3785992511
  namespace: argocd
spec:
  encryptedData:
    project: AgDUh+NVyaFdDXzXYsCaaGlQxifr2NZwIWUFlL3Wqbna6x1s5wVOAcQQcIs5vA+ey8tqxpLnJ14OPVnvi0Yl9FlebmGNJ8Tnpn95VhkZ6rH1xhbI51iwj0R9lR1yLgxIQUvz5QXU0BwWS5J7Oj4DB/4V6jrSe9SXIjRLX6cmRaTairQxlmcZRtD64jeNrvtJ5m1gp6QV9XpcK7KYTuiDyOFU5y7ZweL7owAdyOAg+W1MoWqEASuSsGDkZogcCACid/9/0zCJW000OXcyITWBFex/O0nvF7XTYC1tJad83zRedAwiThc5vlsVwn2+ZQk2LeTqmicgjXKGIOe+mOVZPvfuV67Bc3bT/FT/DisuBJfWfjLOcHKGZxoKt43ZFukYFpYWwpPG6RdZ5GKfNcgaJrA/YVLMUBP5JW/0Nluxij7hLeA3+fjewNFWU07pogf5CpLs7SJBNK2yatMJUrOW+N8eknd9GqQUtlJAtaegNnHUCmTo1dxLYE6wv/18TqJRKoUFfpgEBgXTECPeBi6WSImVrLVgoe8sKQkKhBavtXYFMXNWrbOxYVMr2Mu1tMVnmcqOr/iB7vg7o03PV8UWCP3Ja0tzMlwympWpbLrxe6bvVaiMWa0aYpE0jeoT21R90Mu75+GF7GUgnh89Iaton5ZJOnCq/rhejcNyLuyS/spjk0bAc4V4+tgnC8q1DCayxW/kcbUQbdP2
    type: AgAGCHq7UJQjzzjBhvWyt/Ymo7fBC32eu0UW+3vazSmlvA23pLRXcOzmgslp4cQSKDXW7fftsMc6j1wGbbwOQiRldYjX0tYOEifoSpIMcELwYzn8a79QJBYD6kzcOV2l4lj8QxcNdj/NaoQ65MJ/oWoqJkrD5gfx14xwI4PKdm3N7adxagNQvZQj2O8pPEkczI1ns+5cIR5+3qpkcQbkPt5mYmfixyUMWxJ7HufYxqRFfq/undwCH+/etD9HaQrw822g+k6SaPui/4Hf2GO+722t+UlB+iTwmfGDmIe5CVxMUVIcQsZQ99Br15TPcXsIHmyTArvkJVCKluRP7HY9ubR6i16hTNqEfeT2K1mjlSOowDZLfGO2FRFKQwBwyWElodiYTjwen5IOs584noCg8FXN3JEm9HnbC5AAm+fg5cZPICpIUU4XiJSe9BUC1zoi+w7XLqLEg++g++v1XHYqARf2MjBlbK/nk0TYJXsTcRq8P1FfZe3sQdPWwKe5Ia7XvYlFN3mAEPld9K971eouFuwtdm9LG3Qo5zL/nbrhuJ18wcwRuTBj+jbEeIQEK2w0TNOnQCXRC7bG9MGeuwiV3eKz9udaci4BBuy0p0yLIFCXx4aBXtuwWpuJt40Sp4K2mYbbHelikurxL8myAHYyuGZmJA/XM0dS8RsROnPNIzE2u43Eu6R0OO/mOJQ7fPNHVKqCtCc=
    url: AgADMsKFGYChiwnQIECkMB0ovxI+Vw/tQArqjZ2EsVXZYDHkZSU/G5DhQD64EysVeV/EI0OW+qJ/hvgIwEDnpyaZqAsi2IIEnQRsgx9UKVvAFQ6dBlSjZzfP88fkR8x/mBN6h5X/SRcFQ2d+S0juMNhJM2CfmD8H4YcNOtdpfmN1T56EJoslOPqJr5VucIJ2gMvlCUgEMTT6nr+8n34XAOGyzC+l3qnriw32K40SN0RMIAbglwNy5x5zxUqAXW2h0yUcojEgHdhUkAW2ItdtB5cLWxU7KgfsSnJD7cnh2EJ2IqHfhDxHuKT/12gOtpK0PMVbHJWRl8UijolARitsMKLP8AAkVX7oXVXP16vonDFKFgae1MyIE6Lfl07HSht6u5qlCzancEgnqvNJ9cDnh5UVa7iB851xhwViNP+FCyw16QUt5GWJGVTi1V5rlT0U8ZCQZ0wyryP9dFhTy8Mnz6T5tImEI3SCiCjoN5atoRWTF5lcdgIvNAEJ4ya2xBNK1Wd817yQynX9ZKtBjm2wM0YzLmRhlJx/IQ/fsBWJDiAFRUTMI/ff8iF3N/WR3hsX2vnuFjmCpbXa/rAf7EXahKSVm4dJ7L35+jjebo7BHgkdYZ/0qGimSeP9XKGMQnX2Rt6CqdgqsyLnK7KeIsJGZyXh+vG/M3bjOUkDBevIxnOnXm1CqsKyLPA8NLM0r3liyPhf72SiI4sfFypsIEtKDSNxJYE2foDnMBiQFMCPZrmwZABeItClJhtCC4qgHbk8
  template:
    metadata:
      annotations:
        managed-by: argocd.argoproj.io
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: repo-3785992511
      namespace: argocd
    type: Opaque
