name: Update Image version

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.13.2/yq_linux_amd64.tar.gz -O yq.tar.gz
          tar xzf yq.tar.gz
          sudo mv yq_linux_amd64 /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          yq --version

      - name: Read project-nextjs.yaml
        id: read-file
        run: echo "::set-output name=file-content::$(cat ${{ github.event.client_payload.app_name }}.yaml)"

      - name: Extract current version from YAML file
        id: extract-version
        run: echo "::set-output name=version::$(yq r ${{ steps.read-file.outputs.file-content }} app_version)"

      - name: Update image version in file
        id: update-image
        run: |
          sed -i "s/web\.image: .*$/web\.image: dborovskiy00\/nextjs:${{ steps.extract-version.outputs.version }}/" ${{ steps.read-file.outputs.file-content }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ github.event.client_payload.app_name }}.yaml
          git commit -m ${{ steps.extract-version.outputs.version }}
          git push

      - name: Create and push tag
        run: |
          git tag -a ${{ steps.extract-version.outputs.version }} -m "Version ${{ steps.extract-version.outputs.version }}"
          git push origin ${{ steps.extract-version.outputs.version }}
