name: Update Image version

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update version in YAML file
        run: |
          sed -i "s/^        - name: web\.image$/        - name: web\.image\n          value: dborovskiy00\/nextjs:${{ github.event.client_payload.version }}/" ${{ github.event.client_payload.app_name }}.yaml

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ github.event.client_payload.app_name }}.yaml
          git commit -m "${{ github.event.client_payload.version }}"
          git push

      - name: Create and push tag
        run: |
          git tag -a ${{ github.event.client_payload.version }} -m "Version ${{ github.event.client_payload.version }}"
          git push origin ${{ github.event.client_payload.version }}
